kkebo/swift_os

- .gitignore
- Makefile
- Package.swift
- README.md
- Sources/Kernel/kernel.swift
- Sources/Kernel/putchar.swift
- Sources/Volatile/Volatile.h
- boot.s
- linker.ld
References:
- https://wiki.osdev.org/Raspberry_Pi_Bare_Bones_Rust
- https://wiki.osdev.org/Raspberry_Pi_Bare_Bones
- https://github.com/bztsrc/raspi3-tutorial
> feat: support Raspberry Pi 3 Model B

- Makefile
- Package.swift
- README.md
> build: change the default build target to Raspberry Pi 4 (#13)

- .github/workflows/ci.yml
- README.md
- Sources/Kernel/putchar.swift
To merge this, I need to wait until the Swift main branch to be 6.1.
> fix: fix compilation error in Swift 6.0

- Makefile
- Sources/Kernel/Framebuffer.swift
- Sources/Kernel/kmain.swift
- Sources/Kernel/mbox.swift
- Sources/MailboxMessage/include/mbox.h
closes #12
I tested on my Raspberry Pi 4.
Display:
Serial:
> feat: Framebuffer (#12)

- README.md
I tested this installation steps on Raspberry Pi OS (Bookworm).
> docs: add instructions for Debian 12 to README.md

- Sources/Kernel/Framebuffer.swift
> refactor: refactor `PixelOrder`

- Package.swift
- Sources/Kernel/Framebuffer.swift
[SE-0439](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0439-trailing-comma-lists.md) is now available on Swift main snapshots.
> style: add trailing commas (SE-0439)

- .gitignore
- Makefile
A map file can be useful for debugging.
> chore: generate a map file

- Sources/Kernel/Framebuffer.swift
`subscript` is more convenient.
> refactor: refactor pointer access

- .github/workflows/ci.yml
> ci: change Swift image to nightly-6.1-jammy

- .github/workflows/ci.yml
This makes debugging CI easier.
> ci: print `swift --version`

- Package.swift
- Sources/Kernel/Framebuffer.swift
- Sources/Kernel/mbox.swift
- Sources/Kernel/uart.swift
- Sources/MailboxMessage/include/mbox.h
- Sources/MailboxMessage/mbox.c
https://github.com/kkebo/swift_os/issues/14#issuecomment-2411760709
The size of `kernel.elf` won't be changed.
> refactor: reimplement `mbox` in Swift

- Makefile
> build: fix Makefile dependencies

- Package.swift
- Sources/Support/memcpy.swift
- Sources/Support/memset.swift
> feat: implement `memcpy` and `memset`

- Sources/Support/memmove.swift
> feat: implement `memmove`

- Makefile
- toolset.json
This reverts 0c6ba8e6818b945a1d4d83cf035618ffa2706014.
fixes #80
> revert: build: enable -experimental-hermetic-seal-at-link

- .github/workflows/ci.yml
This PR is a follow-up of #95.
> ci: fix build-linux job

- README.md
This is an alternative to #90.
> docs: add tips about `-experimental-hermetic-seal-at-link`

- Sources/Support/memcpy.swift
- Sources/Support/memmove.swift
- Sources/Support/memset.swift
> fix: use `@_cdecl` in place of `@_silgen_name`

- scripts/ci-install-swift.sh
- https://sipb.mit.edu/doc/safe-shell
- https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425
> ci: `set -euxo pipefail`
