- .github/workflows/ci.yml
This repository is now using swift-format to format its source code. This pull request is adding a CI job that checks swift-format warnings.
> ci: add swift-format lint job

- .github/workflows/ci.yml
fixes #21
`llvm-14` installs LLVM tools with the `-14` suffix, so no conflicts occur.
> ci: do not overwrite builtin LLVM tools

- Makefile
- Package.swift
This option reduces binary sizes.
w/o `-experimental-hermetic-seal-at-link`:
```
-rwxr-xr-x. 1 kebo kebo   792 May  4 02:15 kernel8.img
-rwxr-xr-x. 1 kebo kebo 68168 May  4 02:15 kernel.elf
```
w/ `-experimental-hermetic-seal-at-link`:
```
-rwxr-xr-x. 1 kebo kebo   752 May  4 02:14 kernel8.img
-rwxr-xr-x. 1 kebo kebo 67392 May  4 02:14 kernel.elf
```
> build: enable `-experimental-hermetic-seal-at-link`

- Package.swift
This reduces binary sizes.
`-O` (default):
```
-rwxr-xr-x. 1 kebo kebo   752 May  4 03:34 kernel8.img
-rwxr-xr-x. 1 kebo kebo 67392 May  4 03:34 kernel.elf
```
`-Osize`:
```
-rwxr-xr-x. 1 kebo kebo   541 May  4 03:35 kernel8.img
-rwxr-xr-x. 1 kebo kebo 67208 May  4 03:35 kernel.elf
```
No flags are added to `cSettings` since `dymmy.c` and assembly files are not worth optimizing.
> build: pass swiftc the `-Osize` flag

- .github/workflows/ci.yml
- README.md
- Sources/Kernel/kernel.swift
- Sources/Kernel/putchar.swift
> fix: use `@_cdecl` rathar than `@_silgen_name`

- Package.swift
PackageDescription's `swiftLanguageVersions` is deprecated and replaced by `swiftLanguageModes`.
https://github.com/swiftlang/swift-evolution/blob/main/proposals/0441-formalize-language-mode-terminology.md
> chore: replace deprecated PackageDescription API

- Package.swift
swift_os requires Swift 6.1 toolchain because it's using the experimental feature `Volatile`. So there is no reason to support SwiftPM 6.0.
> build: bump swift-tools-version to 6.1

- Sources/Kernel/Framebuffer.swift
- Sources/Kernel/kmain.swift
fixes #33 
This reverts commit f4d57f9b710de20c7cf04c8ab07e3af7c577a5c1.
> revert: fix: force to use `Framebuffer.shared` instead of an arbitary instance

- Sources/Kernel/Framebuffer.swift
- Sources/Kernel/kmain.swift
This helps avoid hard-coding constants.
> refactor: add parameters to `Framebuffer.init`

- .github/workflows/ci.yml
This change makes the CI job faster.
> ci: add `--parallel` to swift-format

- README.md
Swiftly's repo has been moved.
> docs: fix Swiftly's URL in README.md

- Sources/Kernel/Framebuffer.swift
> chore: do not use `Framebuffer.shared` forever

- README.md
Changes:
- docs: change Swift version requirement from 6.0-snapshot to 6.1-snapshot
Not to change:
- `.github/workflows/ci.yml` (because swiftlang/swift image doesn't have 6.1 tags yet)
> docs: change Swift version requirement from main-snapshot to 6.1-snapshot

- Sources/Kernel/Framebuffer.swift
- Sources/Kernel/mbox.swift
- Sources/Kernel/uart.swift
- Sources/MailboxMessage/include/mbox.h
According to [SE-0412](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0412-strict-concurrency-for-global-variables.md), there is `__attribute__((swift_attr("@MainActor")))` for C and Obj-C. However, there's no `MainActor` in Embedded Swift.
There are two options:
1. Wrapping `MailboxMessage.mbox` with a safer Swift type
2. Ignoring errors by appending `nonisolated(unsafe)` to `mbox`
Option 1 is ideal, but I'm going to work on #42 and `MailboxMessage.mbox` may be removed.
So I've decided to adopt option 2 for now. It can be achieved with `__attribute__((swift_attr("nonisolated(unsafe)")))`. swift_os's kernel is currently single-threaded, so it's safe.
> fix: remove `@preconcurrency` from MailboxMessage

- Makefile
With the `--print-gc-sections` flag, we can get the following outputs:
```
removing unused section .build/release/libKernel.a(boot.S.o):(.text)
removing unused section kernel.elf.lto.o:(.text)
```
These are useful for debugging because we can notice unexpected removing sections immediately.
> build: add `--print-gc-sections` flag to linker

- Makefile
before
```
-rwxr-xr-x 1 kebo kebo  1636 Mar 10 20:28 kernel8.img
-rwxr-xr-x 1 kebo kebo 69064 Mar 10 20:28 kernel.elf
```
after
```
-rwxr-xr-x 1 kebo kebo  1636 Mar 10 20:32 kernel8.img
-rwxr-xr-x 1 kebo kebo 67536 Mar 10 20:32 kernel.elf
```
> build: reduce binary size

- Package.swift
swift_os already requires Swift 6.2 or later, so this change has no risks.
> build: bump swift-tools-version to 6.2

- Package.swift
Swift tools version 6 uses Swift 6 language mode by default, so I don't need to specify language mode explicitly.
> build: remove explicit language mode specification

- .swift-version
- README.md
swiftly will install and use the toolchain written in `.swift-version`.
> chore: add `.swift-version`

- Sources/Kernel/Kernel.swift
- Sources/RaspberryPi/Framebuffer.swift
`MutableSpan` is safer than direct pointer operations.
[SE-0467: MutableSpan](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0467-MutableSpan.md)
> feat(RaspberryPi)!: use `MutableSpan` instead of a pointer

- Makefile
- Package.swift
- Sources/RaspberryPi/mbox.swift
- Sources/Support/memset.swift
I made `Mbox` non-copyable to avoid unexpectedly copying the global variable `mbox`.
It seems that `~Copyable` requires `memset`. So I also added its implementation to the new `Support` module.
```console
$ clang -fuse-ld=lld --target=aarch64-none-none-elf -nostdlib -static -Wl,--gc-sections,--print-gc-sections,--strip-all,--allow-multiple-definition -T linker.ld -Xlinker -Map=kernel.map .build/release/libKernel.a -o kernel.elf
removing unused section .build/release/libKernel.a(boot.S.o):(.text)
removing unused section kernel.elf.lto.o:(.text)
removing unused section kernel.elf.lto.o:(.text.swift_beginAccess)
removing unused section kernel.elf.lto.o:(.text.swift_endAccess)
ld.lld: error: undefined symbol: memset
>>> referenced by <compiler-generated>:0 (/<compiler-generated>:0)
>>> …
```
> refactor: non-copyable `Mbox`

- .github/workflows/ci.yml
I didn't notice the GitHub-hosted arm64 Linux runners were in public preview. I prefer aarch64 to x86_64.
> ci: arm64 Linux runner

- Package.swift
This change reduces the binary size of `libKernel.a`.
> build: add `-mergeable-symbols`

- Makefile
- specify dependencies of each target so that we no longer need to clean build unless the Swift toolchain version is changed
- use more variables so that we can easily change filenames
- put all outputs into `.build` so that `swift package clean` can clean everything
- fix indentation
> build: improve Makefile

- Makefile
- Package.swift
- Sources/AsmSupport/aarch64/boot.S
- toolset.json
This allows SwiftPM to build a final product without an additional linker step. So now our Makefile is purely a task runner, not a build script. This also helps LSP support.
> build: use toolset.json

- linker.ld
- toolset.json
I changed `--orphan-section` from `place` (default) to `error`, and explicitly specified rules in a linker script.
This prevents from forgetting to change a linker script when it need to be changed.
> build: prohibit orphan sections

- .sourcekit-lsp/config.json
Now we can jump to definitions and show documentations and auto completions using SourceKit-LSP.
> chore: fix LSP

- linker.ld
> build: discard `.swift_modhash` section

- .github/workflows/ci.yml
- README.md
This PR is intended to follow the swift-format's change: https://github.com/swiftlang/swift-format/pull/999.
> revert: ci: remove deprecated --strict flag

- Sources/RaspberryPi/Framebuffer.swift
- Sources/RaspberryPi/mbox.swift
- Sources/RaspberryPi/uart.swift
swift-format does not yet fully support `unsafe` expressions, but the only remaining problem is now `NoAssignmentInExpressions`.
> style: partially re-enable lint

- .github/workflows/ci.yml
- .swift-version
To pass CI, we must keep using main-snapshot-2025-05-12 until #101 is resolved.
> build: pin Swift toolchain version to main-snapshot-2025-05-12

- .github/workflows/ci.yml
- .swift-version
Reverts kkebo/swift_os#106
The new toolchain has been released. It’s time to revert the workaround.
> revert: build: pin Swift toolchain version to main-snapshot-2025-05-12

- toolset.json
`-mergeable-symbols` is now the default behavior in Embedded Swift, so we don't need to add the flag manually.
> build: remove `-mergeable-symbols`
